### ISSUE TITLE
Dashboard- FMRI Cross Participant Metrics Not Working for Vipr

### ISSUE THREAD

**Issue by JessDArcey** [TIGRLab/admin#975]

**Comment by djoverton** [comment]
Database was out of date for this project; this should be fixed now.

**Comment by navonacalarco** [comment]
Thanks Dawson! @JessDArcey  Wanna check?

**Comment by navonacalarco** [comment]
Hey@djoverton, @JessDArcey and I still can't see any fMRI metric on 'Subjects' tab for VIPR.

Are we looking at something different?

**Comment by navonacalarco** [comment]
@JessDArcey It seems to work now! Check it out! :dancer:
